
name: Metrics
on:
  # Schedule updates (each hour)
  schedule: [{cron: "0 * * * *"}]
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}

          # Core
          user: mrdvince
          config_timezone: Europe/Amsterdam
          committer_message: "chore: update metrics"
          
          template: classic
          base: header
          
          plugin_isocalendar: yes
          plugin_isocalendar_duration: half-year
          plugin_followup: yes
          plugin_followup_sections: repositories
          plugin_introduction: yes
          plugin_introduction_title: yes
          plugin_languages: yes
          plugin_languages_categories: programming
          plugin_languages_aliases: javascript:JS typescript:TS, Jupyter Notebook:ipynb
          plugin_languages_ignored: javascript, typescript, JS, TS, Jupyter Notebook, ipynb, html, css, tex, less, dockerfile, makefile, qmake, lex, cmake, shell,gnuplot
          
          plugin_languages_colors: github
          plugin_languages_limit: 6
          plugin_languages_recent_categories: programming
          plugin_languages_recent_days: 365
          plugin_languages_recent_load: 300
          plugin_languages_sections: most-used
          plugin_languages_threshold: 0%
          
